[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs", "npm", "caddy"]

[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-dev --no-scripts --no-interaction",
  "npm install",
  "npm run build"
]

[phases.build]
cmds = [
  "mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache",
  "chmod -R 775 storage bootstrap/cache",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "caddy run --config /app/Caddyfile"